export const FETCH_POSTS = "FETCH_POSTS";
export const NEW_POST = "NEW_POST";

export const EVENT_LOGIN_NOK = "EVENT_LOGIN_NOK";
export const EVENT_LOGIN_OK = "EVENT_LOGIN_OK";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const FETCH_ANNOUNCEMENTS = "FETCH_ANNOUNCEMENTS";
export const NEW_ANNOUNCEMENT = "NEW_ANNOUNCEMENT";
export const CLEAR_NEW_ANNOUNCEMENT = "CLEAR_NEW_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";
export const SHOW_ANNOUNCEMENT_FOR_UPDATE = "SHOW_ANNOUNCEMENT_FOR_UPDATE";
